---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangboyuan.
--- DateTime: 2020/7/29 20:43
---
--切换场景
function SwitchScence(scence)
    -- 将重要的函数赋予空值，以免冲突
    love.update = nil
    love.draw = nil
    love.keypressed = nil

    -- 将需要的场景加载进来，并执行load函数
    love.filesystem.load ('Scences/'..scence..'.lua') ()
    love.load ()
end

function ReSetPanel()
    clearButton()
    clearPieces()
end