
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangboyuan.
--- DateTime: 2020/8/3 20:50
---

local class = require("middleclass")
local network = require("network")
DrawnWindow = class("DrawnWindow")
local drawn = {}
local originalFont = love.graphics.getFont()

function DrawnWindow:initialize(type)
    if drawn[1] then
        print("has window~~~")
        return
    end
    self.live = 1000
    self.type = type
    self.textColor = {0.1,0.1,0.1}
    self.font = love.graphics.getFont(10)
    self.color = {0.4,0.4,0.4}
    self.originalColor = self.color
    self.x = 10
    self.y = 500
    self.isSet = false
    self.move = -150
    --drawn = self
    drawn[1] = self
    --table.insert(drawn,self)
    return self
end

function DrawnWindow:update()
    local x, y = love.mouse.getX(), love.mouse.getY()
    if x < self.x + 50 and x > self.x and y < self.y + 30 and y > self.y then
        if love.mouse.isDown(1) then
            if not self.isSet then
                --network.send()
                self.isSet = true
                _OnConfirm(self.type)
            end
        end
    end

    if x < self.x+50 + 70 and x > self.x+70 and y < self.y + 30 and y > self.y then
        if love.mouse.isDown(1) then
            if not self.isSet then
                --network.send()
                self.isSet = true
                _OnConfuse(self.type)
            end
        end
    end
    self.live = self.live - 1
    if self.live < 0 then
        _OnConfuse(self.type)
    end
end

function DrawnWindow:draw()
    love.graphics.setColor({ 0.9,0.9,0.9 })
    love.graphics.rectangle("fill", self.x + self.move, self.y, 130, 30)
    love.graphics.print(self.type, love.graphics.newFont(30),self.x, self.y - 30)
    love.graphics.setFont(self.font)
    --love.graphics.setColor(self.color)
    --love.graphics.rectangle("fill", self.x, self.y, 30, 30)
    love.graphics.setColor(self.textColor)
    love.graphics.print("Confirm", self.x + 10+ self.move, self.y + 10)

    --love.graphics.setColor(self.color)
    --love.graphics.rectangle("fill", self.x+70, self.y, 30, 30)
    love.graphics.setColor(self.textColor)
    love.graphics.print("Confuse", self.x + 80+ self.move, self.y + 10)
    if self.move < 0 then
        self.move = self.move + 3
    end
    love.graphics.setColor(1,1,1)
    love.graphics.setFont(originalFont)
end

function updateDrawnWindow()
    for i, v in pairs(drawn) do
        v:update()
    end
end

function drawDrawnWindow()
    for i, v in pairs(drawn) do
        v:draw()
    end
end

function clearDrawnWindow()
    drawn = {}
end

function _OnConfirm(type)
    print("Confirm!!!".."    "..type)
    if type == "drawn" then
        local _json = {}
        _json.Ext = "yes"
        _json.Op = 4
        network.send(_json,1)
    end
    clearDrawnWindow()
end

function _OnConfuse(type)
    print("Confuse!!!".."    "..type)
    if type == "drawn" then
        local _json = {}
        _json.Ext = "no"
        _json.Op = 4
        network.send(_json,1)
    end
    clearDrawnWindow()
end