---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangboyuan.
--- DateTime: 2020/7/30 12:37
---


local class = require("middleclass")
local network = require("network")
piece = class("piece")
local pieces = {}
--local originalFont = love.graphics.getFont()
canbeSet = true
local lastpieceid = nil

function piece:initialize(x, y,i,j,id,color)
    self.x = x
    self.y = y
    self.color = {0,0,0}
    self.originalColor = self.color
    self.i = i
    self.j = j
    self.islast = false
    self.beSetted = false

    self.id = self.i + (self.j * 100)
    pieces[self.id] = self
    --table.insert(pieces, self)
    return self
end

function piece:update()
    local x, y = love.mouse.getX(), love.mouse.getY()
    if x < self.x + 20 and x > self.x and y < self.y + 20 and y > self.y then
        if not self.beSetted and canbeSet then
            if love.mouse.isDown(1) then
                local _body = {}
                _body.x = self.i - 1
                _body.y = self.j - 1
                network.send(_body,1)
                --self.beSetted = true
                --print(self.i.." "..self.j.." "..self.id)
                PieceBeSetOff()
            end
        end
        --self.color = {self.color[1] + 20, self.color[2] + 20, self.color[3] + 20}
    else
        --self.color = self.originalColor
    end
end

function piece:draw()

    if   self.beSetted then
        if self.islast then
            love.graphics.setColor({1,0.1,0.5 })
            love.graphics.circle("fill", self.x+10, self.y+10, 11) -- Draw white circle with 100 segments.
        end
        love.graphics.setColor(self.color)
        love.graphics.circle("fill", self.x+10, self.y+10, 10) -- Draw white circle with 100 segments.
    end


end

function updatePieces()
    for i, v in pairs(pieces) do
        v:update()
    end
end

function drawPieces()
    for i, v in pairs(pieces) do
        v:draw()
    end
end

function clearPieces()
    lastpieceid = nil
    pieces = {}
end

function PieceBeSetOn()
    canbeSet = true
    --TODO：当前谁的回合以及最后落子位置
end

function PieceBeSetOff()
    canbeSet = false
end

function ServerPieceSet(x,y,StepNum)
    local id = x + (y * 100)
    if StepNum % 2 == 0 then
        pieces[id].color = {1,1,1}
    else
        pieces[id].color = {0,0,0}
    end
    pieces[id].beSetted = true
    pieces[id].islast = true
    if lastpieceid ~= nil then
        pieces[lastpieceid].islast = false
    end
    lastpieceid = id
end