---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangboyuan.
--- DateTime: 2020/8/3 16:11
---

local class = require("middleclass")
local network = require("network")
player = class("player")
local players = {}
local originalFont = love.graphics.getFont()

function player:initialize(name,x,y)

    self.text = name
    self.x = x
    self.y = y
    self.textColor = {0.8,0.8,0.8}
    self.font = love.graphics.getFont(10)
    self.color = {0.4,0.4,0.4}
    self.originalColor = self.color

    self.beInvited = false
    self.id = #players + 1
    table.insert(players, self)
    return self
end

function player:update()
    local x, y = love.mouse.getX(), love.mouse.getY()
    if x < self.x + self.font:getWidth(self.text) + 20 and x > self.x and y < self.y + self.font:getHeight(self.text) + 20 and y > self.y then
        if love.mouse.isDown(1) then
            if not self.beInvited then
                --network.send()
                print("invit!!!"..self.text)
                self.beInvited = true
            end
        end
        self.color = {self.color[1] + 20, self.color[2] + 20, self.color[3] + 20}
    else
        self.color = self.originalColor
    end
end

function player:draw()
    love.graphics.setFont(self.font)

    love.graphics.setColor(self.color)
    if self.text == "" then
        love.graphics.rectangle("fill", self.x, self.y, 20, 20)
    else
        love.graphics.rectangle("fill", self.x, self.y, self.font:getWidth(self.text) + 20, self.font:getHeight(self.text) + 20)
    end

    love.graphics.setColor(self.textColor)
    love.graphics.print(self.text, self.x + 10, self.y + 10)

    love.graphics.setColor(1,1,1)
    love.graphics.setFont(originalFont)
end

function updateplayer()
    for i, v in pairs(players) do
        v:update()
    end
end

function drawplayer()
    for i, v in pairs(players) do
        v:draw()
    end
end

function clearplayer()
    players = {}
end