---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangboyuan.
--- DateTime: 2020/7/30 8:57
---
---
--五子棋棋盘15×15
require("Function")
require('button')
require("piece")

local curPiece = {}
local debugtext = "Hello World Game Gobang!!"

function love.load() --资源加载回调函数，仅初始化时调用一次
    love.graphics.setBackgroundColor(100,100,100)
    ReSetPanel()
    SetPiece()

end



function love.update(dt) --更新回调函数，每周期调用
    updateButtons()
    updatePieces()


end




function love.draw() --绘图回调函数，每周期调用
    drawButtons()
    DrawQIPAN()
    drawPieces()
    love.graphics.print(debugtext, 600, 300)



end



function love.keypressed(key) --键盘检测回调函数，当键盘事件触发是调用





end



function love.mousepressed(x,y,key) --回调函数释放鼠标按钮时触发。





end

function DrawQIPAN()
    local firstP = {20,20}
    local secondP = {20,440}
    for i = 1, 15 do
        love.graphics.line(firstP[1],firstP[2],secondP[1],secondP[2])
        firstP[1] = firstP[1] + 30
        secondP[1] = secondP[1] + 30
    end
    local firstP = {20,20}
    local secondP = {440,20}
    for i = 1, 15 do
        love.graphics.line(firstP[1],firstP[2],secondP[1],secondP[2])
        firstP[2] = firstP[2] + 30
        secondP[2] = secondP[2] + 30
    end
end

function SetPiece()
    local px = 10
    local py = 10
    for i = 1, 15 do
        for j = 1, 15 do
            piece:new(px,py)
            px = px + 30
        end
        py = py + 30
        px = 10
    end
end

