---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangboyuan.
--- DateTime: 2020/7/30 11:30
---
require("Function")

function love.load() --资源加载回调函数，仅初始化时调用一次
    love.graphics.setBackgroundColor(100,100,100)



end



function love.update(dt) --更新回调函数，每周期调用




end




function love.draw() --绘图回调函数，每周期调用

    love.graphics.print('Matching', 380, 300)

end



function love.keypressed(key) --键盘检测回调函数，当键盘事件触发是调用





end



function love.mousepressed(x,y,key) --回调函数释放鼠标按钮时触发。





end