---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangboyuan.
--- DateTime: 2020/7/30 8:57
---
---
--五子棋棋盘15×15
require("Function")
require('Component/Button')
require("Component/piece")
require("Component/DrawnWindow")
local json = require("json")
local network = require("network")

local curPiece = {}
local debugtext = "Hello World Game Gobang!!"
local myScore = 0
local TargetScore = 0
local winlose = 0
local index = 1
local isEnd = false
local isOneMore = false

function love.load() --资源加载回调函数，仅初始化时调用一次

    ReSetPanel()

    network.recvMsgFunc = function(data)
        GameCallBack(data)
    end

end



function love.update(dt) --更新回调函数，每周期调用
    network.update()
    updatePieces()
    updateButtons()
    updateDrawnWindow()
    if isEnd then
        EndDraw()
    end
end




function love.draw() --绘图回调函数，每周期调用
    tellBorW()
    DrawQIPAN()
    drawPieces()
    DrawPlayerView()
    drawDrawnWindow()
    drawButtons()
    if isEnd then
        EndDraw()
    end
end



function love.keypressed(key) --键盘检测回调函数，当键盘事件触发是调用
end



function love.mousepressed(x,y,key) --回调函数释放鼠标按钮时触发。
end


--region 界面逻辑
function InitSet()
    love.graphics.setBackgroundColor(0.3,0.3,0.3)
    clearButton()
    clearPieces()
    clearplayer()
    clearDrawnWindow()
    winlose = 0
    index = 1
    isEnd = false
    isOneMore = false
end

function tellBorW()
    love.graphics.setColor({1,1,1})
    love.graphics.print("Your Color", 600, 200)
    if MyP == "B" then
        love.graphics.setColor({0,0,0})
        love.graphics.circle("fill", 650, 250, 30)
    end
    if MyP == "W" then
        love.graphics.setColor({1,1,1})
        love.graphics.circle("fill", 650, 250, 30)
    end
    if canbeSet then
        love.graphics.print("Your Turn!!!!!!!", 600, 300)
    end

end

function ReSetPanel()
    InitSet()
    SetPiece()
    button:new(function()
        OnRegret()
        print("Regret")
    end,"Regret", 700, 400, 5, 5, {1,0,0}, love.graphics.newFont(10))
    button:new(function()
        OnDrawn()
        print("drawn")
    end,"drawn", 700, 460, 5, 5, {1,0,0}, love.graphics.newFont(10))
    button:new(function()
        OnGiveup()
        print("Give UP")
    end,"give up", 700, 530, 5, 5, {1,0,0}, love.graphics.newFont(10))
end

function DrawQIPAN()
    local firstP = {20,20}
    local secondP = {20,440}
    love.graphics.setColor({ 0.5,0.5,0.5 })
    local id = 1
    for i = 1, 15 do
        love.graphics.line(firstP[1],firstP[2],secondP[1],secondP[2])
        firstP[1] = firstP[1] + 30
        secondP[1] = secondP[1] + 30
    end
    local firstP = {20,20}
    local secondP = {440,20}
    for i = 1, 15 do
        love.graphics.line(firstP[1],firstP[2],secondP[1],secondP[2])
        firstP[2] = firstP[2] + 30
        secondP[2] = secondP[2] + 30
    end
end

function DrawPlayerView()
    love.graphics.setColor({1,1,1})
    love.graphics.print(debugtext, 600, 100)
    --love.graphics.print("Me", 600, 150)
    --love.graphics.print("Opponent", 600, 200)
    --love.graphics.print(myScore, 600, 170)
    --love.graphics.print(TargetScore, 600, 220)
end

function SetPiece()
    local px = 10
    local py = 10
    local id = 1
    for i = 1, 15 do
        for j = 1, 15 do
            piece:new(px,py,i,j,id)
            px = px + 30
            id = id + 1
        end
        py = py + 30
        px = 10
    end
end

function SetScore()

end

function EndDraw()
    love.graphics.setColor({0.5,0.5,1})
    if winlose == 1 then
        love.graphics.print("you win!!!", love.graphics.newFont(30),300, 300)
    elseif winlose == 0 then
        love.graphics.print("you lose!!!", love.graphics.newFont(30),300, 300)
    elseif winlose == 2 then
        love.graphics.print("Drawn!!!", love.graphics.newFont(30),300, 300)
    end
    if index == 1 then
        button:new(function()
            OnOneMore()
        end,"One More", 300, 400, 5, 5, {1,0,0}, love.graphics.newFont(30))
        button:new(function()
            OnGameQuit()
            --SwitchScence('Hall')
        end,"Quit", 330, 500, 5, 5, {1,0,0}, love.graphics.newFont(30))
        index = index + 1
    end

end
--endregion

--region 按钮事件

function OnOneMore()
    if not isOneMore then
        print("One More")
        local _body = {}
        _body.Action = 6
        _body.Sender = {}
        _body.Sender = MyPlayer
        --_body.Sender.ID = MyID
        _body.RommID = RoomID
        network.send(_body,6)
        isOneMore = true
        --InitSet()
        --ReSetPanel()
    end
end

function OnGameQuit()
    local _json = {}
    _json.Action = 3
    _json.Sender = MyPlayer
    network.send(_json,6)
    SwitchScence('Hall')
end

function OnDrawn()
    local _json = {}
    _json.Op = 3
    _json.Ext = MyID
    _json.RommID = RoomID
    network.send(_json,1)
end

function OnRegret()

end

function OnGiveup()
    if not isEnd then
        local _json = {}
        _json.Op = 5
        _json.Ext = MyID
        _json.RommID = RoomID
        network.send(_json,1)
    end
end
--endregion

--region callback
function GameCallBack(data)
    local _json = data
    if _json.CMD == 1 then
        local body = json.decode(_json.Body)
        local x = body.X + 1
        local y = body.Y + 1
        local Result = body.Result
        local StepNum = body.StepNum-1
        local Op = body.Op
        local Ext = body.Ext
        print(x.."   "..y.."   "..Result.."   "..StepNum)
        --和棋
        if Op == 4 then
            if Ext == "draw" then
                winlose = 2
                isEnd = true
            end
            if Ext == "noDraw" then
                clearDrawnWindow()
            end
        end
        if Op == 0 then
            if Result == 1 then
                ServerPieceSet(x,y,StepNum)
                if StepNum % 2 ~= 0 and MyP == "W" then
                    print("WWWWWW")
                    PieceBeSetOn()
                end
                if StepNum % 2 == 0 and MyP == "B" then
                    print("BBBBBBBBB")
                    PieceBeSetOn()
                end
            end
        end

        if Result == 5 then
            --正常落子结束
            if Op == 0 then
                ServerPieceSet(x,y,StepNum)
                if StepNum % 2 ~= 0 and MyP == "B" then
                    winlose = 1
                end
                if StepNum % 2 == 0 and MyP == "W" then
                    winlose = 1
                end
                isEnd = true
            end
            --认输
            if Op == 5 then
                if Ext == MyID then
                    winlose = 0
                else
                    winlose = 1
                end
                isEnd = true
            end
        end

        if Result == 0 then
            if Op == 3 and Ext ~= MyID then
                DrawnWindow:new("drawn")
            end
        end


    end

    if _json.CMD == 7 then
        local body = json.decode(_json.Body)
        fP = body.FirstPlayer
        sP = body.LastPlayer
        RoomID = body.RoomID
        --print(fP.."   "..sP.."  "..RoomID)
        if fP.ID == MyID then
            MyPlayer = fP
            PieceBeSetOn()
            MyP = "B"
        else
            MyPlayer = sP
            PieceBeSetOff()
            MyP = "W"
        end
        ReSetPanel()
    end


end


--endregion