---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangboyuan.
--- DateTime: 2020/7/30 11:30
---
require("Function")
local network = require("network")
local t = 0

function love.load() --资源加载回调函数，仅初始化时调用一次
    love.graphics.setBackgroundColor(0.3,0.3,0.3)
    --network.connet("192.168.92.204", "12345")
    --network.connectedFunc = function()
    --    print("connect ok!")
    --end
    --network.disconnectFunc = function()
    --    print("disconnect!")
    --end
    --network.recvMsgFunc = function(msg)
    --    print("recv=>",msg," size=",string.len(msg))
    --end

end



function love.update(dt) --更新回调函数，每周期调用
    --network.update()
    --
    --if t%100==0 then
    --    local dg = string.format("%d", t)
    --    network.send(dg)
    --end
    --t = t + 1

end




function love.draw() --绘图回调函数，每周期调用

    love.graphics.print('Matching', 380, 300)
    love.graphics.print("ServerHost"..ServerHost.."MyID"..MyID.."Myscore"..Myscore, 50, 50)
end



function love.keypressed(key) --键盘检测回调函数，当键盘事件触发是调用





end



function love.mousepressed(x,y,key) --回调函数释放鼠标按钮时触发。





end